-- Load file generated by installer
Cauldron = setmetatable({}, {
    __index = enumKeys,
    __tostring = function()
        return "Cauldron " .. Cauldron.versionString()
    end
})

-- Dynamic stuff
function Cauldron.version() return %i end
function Cauldron.versionString() return %q end
function Cauldron.libraryPath(sub) return %q .. sub end
               
-- Loading helpers
local function _scan(dir)
    dir = dir .. "/"
    local files = fs.list(dir)
    for _, v in ipairs(files) do
        if fs.isDir(dir .. v) then
            _scan(dir .. v)
        else
            shell.run(dir .. v)
        end
    end
end

Cauldron._loaded = {}

-- Actual load function
function Cauldron.loadModule(name)
    if Cauldron._loaded[name] then return end
    _scan(Cauldron.libraryPath(name))
    Cauldron._loaded[name] = true
end

-- API basics
shell.run(Cauldron.libraryPath("middleclass.lua"))
shell.run(Cauldron.libraryPath("CEnum.lua"))
Cauldron.loadModule("CCore")

-- Register apps

